let date=new Date()
console.log(date)
console.log(date.toString())
console.log(date.toLocaleString())
console.log(date.toDateString())
console.log(date.toTimeString())
console.log(date.getHours())
console.log(date.toLocaleTimeString())
console.log(date.getMinutes())
console.log(date.toISOString())
console.log((typeof date))

const time=Date.now()
console.log(time)
console.log(time.getTime())